### ISSUE TITLE
Refactor UploadToDavDialog into class

### ISSUE THREAD

**Issue by sanchezfauste** [Zimbra-Community/owncloud-zimlet#174]
Hi Barry, my partner @adriangibanelbtactic has suggested to me to refactor all the code of the file `zimlet/UploadToDavDialog.js` in a class, to avoid to execute all this code if the zimlet is disabled.

What do you think?

**Comment by barrydegraaff** [comment]
Hello,

I can understand why you would want to do this, however I believe this is implementation
is used on other places throughout Zimbra as well. It is ugly, but it is the same as
for example briefcase I believe.

In case you want to improve the product, I could use automated testing, something like
selenium. So that we can test these refactors.

I personally am not a supporter of changing stuff that works. 

At this time, this is the manual test script:
https://github.com/Zimbra-Community/owncloud-zimlet/blob/soapServiceBarry/test/checklist-for-testing.pdf

Regards, Barry

**Comment by barrydegraaff** [comment]
Anyway, I welcome the pull request, but don't forget to test it thoroughly.

**Comment by sanchezfauste** [comment]
Thanks for the feedback. We will try to implement this modification later, since now we do not have the necessary time.
