### ISSUE TITLE
Enable right click "save to webdav" for folders and muliple email selections

### ISSUE THREAD

**Issue by putt1ck** [Zimbra-Community/owncloud-zimlet#209]
When a project completes it would be useful for any important emails to be saved with the project in folder in <insert name of preferred webdav target here>. Right now this can be done with right-clicking an email, but if a user has a lot of emails to move doing one by one doesn't make sense. 

Additionally the user may well have already moved the emails to a project mailbox folder, so being able to save that whole folder to the project space may be preferable (i.e. there is already an easy way to move emails to a folder, so they complete that process then save the folder).

Related or alternative solution: enable drag and drop of items to webdav zimlet

**Comment by barrydegraaff** [comment]
This used to be possible by dragging and dropping onto the menu item under Zimlets. 

However it was removed. 

The right click menu option, should be multi-select, but for some reason, it is no longer so. 

That needs to be fixed again. 


Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by putt1ck** [comment]
Any news on this one?

**Comment by barrydegraaff** [comment]
No news, I currently have no time scheduled to work on this.

Also while I could hack this in the Javascript part of the Zimlet,
it would be better for reliability to make the back-end support
batch operations. But for now it does not. So that needs to be build as well.

Anyway, as long as this ticket is open, it may be picked up whenever
the next version comes out. Usually when some customer funds some dev time.

**Comment by barrydegraaff** [comment]
Multi-select fix has been pushed to git
