### ISSUE TITLE
Use Zimbra Login Credentials to Login at Webdav 

### ISSUE THREAD

**Issue by acullmann** [Zimbra-Community/owncloud-zimlet#225]
Dear devs,

We are currently evaluating a way to connect our Zimbra installation with our Nextcloud. So far the owncloud-zimlet seems very promising!

Our users can login at both systems with the same credentials (provisioned by a IAM system). So it would be awesome if we do not have to store passwords in Zimbra but use the login password the user entered on Zimbra login again. Similar Nextcloud can do it with samba shares.

As far as I understand this is not possible right now? It would be awesome for our usecase :-) (Does zimbra allow you to get the userpassword?)

Cheers
Alex

**Comment by barrydegraaff** [comment]
Hello Alexander, 

Right now it is not supported, because Nextcloud does not have an API to log-on. 

Ideally the Zimlet would make an API call with admin (or so) credentials to obtain 
a token for the user. 

In the mean time, a work-around is using app passcodes (see the readme), but so 
far nobody has that automated. 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0
