### ISSUE TITLE
Zimbra WebDAV Client for Mega.nz

### ISSUE THREAD

**Issue by protontrigg3r** [Zimbra-Community/owncloud-zimlet#281]
Is it possible to adjust the configuration to use this Zimlet also for other services as well? (I'm interested in [MEGA-WEBDAV](https://github.com/meganz/MEGAcmd/blob/master/contrib/docs/WEBDAV.md))

**Comment by barrydegraaff** [comment]
Yes you can rebrand the Zimlet, example script that you can run on Zimbra:
https://github.com/Zimbra-Community/owncloud-zimlet/blob/soapServiceBarry/nuxeo-labels.sh

But instead of Nuxeo, you put whatever name you want.

Please note, only WebDAV is supported, so if Mega supports that, it should work.
