### ISSUE TITLE
Zimlet privileges in cos via webAdmin

### ISSUE THREAD

**Issue by sematuszewski** [Zimbra-Community/owncloud-zimlet#67]
Zimlet is not visible in the COS tab (ZIMLET privileges)

**Comment by barrydegraaff** [comment]
This is by design to avoid issues like:
https://github.com/Zimbra-Community/owncloud-zimlet/issues/62

And this:
https://bugzilla.zimbra.com/show_bug.cgi?id=96838

However, you can still use a ZIP file for deployment. 

cd /opt/zimbra/zimlets-deployed/_dev/tk_barrydegraaff_owncloud_zimlet/
zip -r tk_barrydegraaff_owncloud_zimlet.zip *
cp tk_barrydegraaff_owncloud_zimlet.zip /tmp/
rm -Rf /opt/zimbra/zimlets-deployed/_dev/tk_barrydegraaff_owncloud_zimlet/

You can then deploy the zip with zmzimletctl (using /tmp/tk_barrydegraaff_owncloud_zimlet.zip)
